Ангарск = = = data-city="angarsk"
Ачинск = = = data-city="achinsk"
Благовещенск = = = data-city="blagoveshhensk"
Братск = = = data-city="bratsk"
Владивосток, Кирова, 5 = = = data-city="vladivostok_kirova"
Владивосток, Русская, 46б = = = data-city="vladivostok_russkaya"
Волгодонск = = = data-city="volgodonsk"
Иркутск, Карла Либкнехта, 9 = = = data-city="irkutsk_karla"
Иркутск, Свердлова, 11 = = = data-city="irkutsk_sverdlova"
Иркутск, Шевцова, 10 = = = data-city="irkutsk_shevcova"
Кемерово, Советский пр-т, 4а = = = data-city="kemerovo_sovetskij_4"
Кемерово, Советский пр-т, 6 = = = data-city="kemerovo_sovetskij_6"
Киров = = = data-city="kirov"
Комсомольск-на-Амуре = = = data-city="komsomolsk"
Красноярск, Аэровокзальная, 17 = = = data-city="krasnoyarsk_aerovokzalnaya"
Красноярск, Красной Армии, 10 = = = data-city="krasnoyarsk_krasnoj"
Красноярск, Кр. Рабочий, 126а = = = data-city="krasnoyarsk_rabochij"
Красноярск, ул. Мужества 4 = = = data-city="krasnoyarsk_muzhestva"
Курган = = = data-city="kurgan"
Магадан = = = data-city="magadan"
Мурманск = = = data-city="murmansk"
Набережные Челны = = = data-city="naberezhnye_chelny"
Находка = = = data-city="nahodka"
Нижнекамск = = = data-city="nizhnekamsk"
Нижний Новгород = = = data-city="nizhnij_novgorod"
Новосибирск, Большевистская, 131 = = = data-city="novosibirsk_bolshevistskaya"
Новосибирск, Нем.-Данченко, 122а = = = data-city="novosibirsk_danchenko"
Новосибирск, ул. Никитина 18/1 = = = data-city="novosibirsk_nikitina"
Петропавловск-Камчатский = = = data-city="petropavlovsk_kamchatskij"
Ростов-на-Дону = = = data-city="rostov"
Самара = = = data-city="samara"
Серов = = = data-city="serov"
Томск = = = data-city="tomsk"
Тюмень, ул. Гнаровской, 12 к. 8 = = = data-city="tumen_gnarovskoj"
Тюмень, ул. Республики, 196а = = = data-city="tumen_respubliki"
Уссурийск = = = data-city="ussurijsk"
Хабаровск = = = data-city="khabarovsk"
<!--  -->
Казахстан:
Алматы, Бегалина, 26а = = = data-city="almaty_begalina"
Алматы, Гагарина, 139/2 = = = data-city="almaty_gagarina"
Алматы, Макатаева, 127 Б = = = data-city="almaty_makataeva"
Астана, А. Жангельдина, 30 = = = data-city="astana_zhangeldina"
Астана, Куйши Дина, 30/2 = = = data-city="astana_dina"
Караганда = = = data-city="karaganda"
Талдыкорган = = = data-city="taldykorgan"